// FLEURON EXTRACTION — a one-off that produced assets/covers/fleuron-2766.mjs.
//
//   node scripts/covers/extract-fleuron.mjs            # print, do not write
//   node scripts/covers/extract-fleuron.mjs --write    # regenerate the asset
//
// ── WHY THE ASSET EXISTS AT ALL ──────────────────────────────────────────────────────────
// The brief specified converting U+2766 FLORAL HEART to a vector path once and shipping the
// path, on the stated grounds that the glyph is "not present in either family" and that the
// obvious source, FreeSerif, is GPL — an extracted outline from which is exactly the murky
// licence the brief existed to escape.
//
// THE PREMISE IS FALSE, and it is worth writing down precisely because it changes the
// licence answer completely. U+2766 is present in ALL THREE vendored faces; EB Garamond
// carries U+2766 and U+2767 both. So the glyph is taken from EBGaramond-Regular.ttf, the
// OFL font already vendored for the eyebrow, descriptor and footer. There is no third font,
// no GPL, and nothing to launder.
//
// The path is still shipped rather than drawn as text, and that is the half of the brief's
// instruction which survives its false premise. A path is geometry: it cannot be altered by
// a font-cache lookup, a fallback face, or a future engine that decides to apply a different
// shaping to a lone symbol run. It is the one element on the cover that is pure decoration
// with no linguistic content, so nothing is lost by freezing it, and reproducibility is won.
//
// ── THE NORMALISATION ────────────────────────────────────────────────────────────────────
// The outline is emitted at a 1000-unit em regardless of the source font's unitsPerEm, in
// y-DOWN screen coordinates with the origin on the baseline, so the renderer scales by
// (size / 1000) and nothing else. EB Garamond happens to be 1000 upm already, which makes
// the normalisation a no-op today and load-bearing the day the source font changes.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import opentype from 'opentype.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const SRC = join(ROOT, 'assets/covers/fonts/EBGaramond-Regular.ttf');
const OUT = join(ROOT, 'assets/covers/fleuron-2766.mjs');

const buf = readFileSync(SRC);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
const glyph = font.charToGlyph('❦');
if (!glyph || glyph.index === 0) throw new Error('U+2766 resolved to .notdef in ' + SRC);

const upm = font.unitsPerEm;
const path = glyph.getPath(0, 0, 1000);   // opentype emits y-down already
const d = path.toPathData(3);
const bb = path.getBoundingBox();
const advance = (glyph.advanceWidth * 1000) / upm;
const pathSha = createHash('sha256').update(d).digest('hex');
const fontSha = createHash('sha256').update(buf).digest('hex');

console.log(`source        ${SRC.replace(ROOT + '/', '')}`);
console.log(`font sha256   ${fontSha}`);
console.log(`glyph         index ${glyph.index}  name "${glyph.name}"  unitsPerEm ${upm} → 1000`);
console.log(`advance       ${advance.toFixed(3)}`);
console.log(`bbox          x ${bb.x1.toFixed(1)}…${bb.x2.toFixed(1)}   y ${bb.y1.toFixed(1)}…${bb.y2.toFixed(1)}`);
console.log(`commands      ${path.commands.length}`);
console.log(`path sha256   ${pathSha}`);

if (!process.argv.includes('--write')) {
  console.log('\n(dry run — pass --write to regenerate assets/covers/fleuron-2766.mjs)');
  process.exit(0);
}

const asset = `// U+2766 FLORAL HEART — the cover fleuron, frozen as geometry.
//
// GENERATED by scripts/covers/extract-fleuron.mjs. Do not hand-edit: the SHA below is
// asserted by tests/covers/determinism.test.mjs, and an edit that changes the outline
// changes every cover in the library.
//
// ── SOURCE AND LICENCE ───────────────────────────────────────────────────────────────────
//   glyph    U+2766 FLORAL HEART ("${glyph.name}", glyph index ${glyph.index})
//   font     EB Garamond, Regular 400 — assets/covers/fonts/EBGaramond-Regular.ttf
//   licence  SIL Open Font License 1.1 — assets/covers/fonts/OFL-EBGaramond.txt
//   holder   Copyright The EB Garamond Project Authors (github.com/octaviopardo/EBGaramond12)
//   font sha ${fontSha}
//
// The OFL permits this. §1 grants the right to use, study, modify and redistribute the
// software; an outline extracted from the font and redistributed is a Modified Version, and
// the only obligations that attach are that it not be sold on its own (§1) and that it not
// be distributed under the reserved name (§5). It is not sold, and this file is not named
// "EB Garamond". The licence text is vendored beside the font it covers.
//
// NOTE for anyone re-deriving this: the brief specified sourcing the glyph from somewhere
// other than these two families, on the belief that neither contained U+2766. Both do.
// There is no reason to reach for a third font, and a positive reason not to — the obvious
// candidate, FreeSerif, is GPL.
//
// ── COORDINATES ──────────────────────────────────────────────────────────────────────────
// A 1000-unit em, y-DOWN (screen convention), origin on the baseline. To draw at size S,
// scale by S/1000. Normalised on extraction, so this holds whatever upm the source uses.

/** The outline, as SVG path data. */
export const FLEURON_PATH = '${d}';

/** SHA-256 of FLEURON_PATH. The determinism anchor; asserted by the test suite. */
export const FLEURON_PATH_SHA256 = '${pathSha}';

/** Advance width at a 1000-unit em. */
export const FLEURON_ADVANCE = ${advance};

/** Ink bounds at a 1000-unit em, y-down. Used to centre the mark on its ink, not its box. */
export const FLEURON_BBOX = Object.freeze({
  x1: ${bb.x1}, y1: ${bb.y1}, x2: ${bb.x2}, y2: ${bb.y2},
});
`;
writeFileSync(OUT, asset);
console.log(`\nwrote ${OUT.replace(ROOT + '/', '')}  (${asset.length} bytes)`);
