/* eslint-disable */
// ═══════════════════════════════════════════════════════════════════════════════════════
// THE KILL SWITCH — a self-destructing service worker.
//
// HOW TO FIRE IT
//
//   cp scripts/sw-kill.js public/sw.js && git commit -am "Kill the shelf service worker" && git push
//
// That is the whole procedure. Do not edit this file under pressure; copy it.
//
// WHY IT WORKS
//
// The browser byte-compares /sw.js against its installed copy on every navigation, and
// /sw.js is served with `Cache-Control: no-cache, must-revalidate` (see public/_headers,
// where that rule exists for exactly this reason). So the moment this file is what the
// edge is serving, every affected reader picks it up on their next navigation — no flag
// service, no dependency on page JavaScript running, no waiting for anyone.
//
// Unlike public/sw.js, this worker DOES call skipWaiting(). It is the only service worker
// in this repo that may: a kill switch that politely waits for the old worker's clients to
// close is not a kill switch. It then deletes every cache it can see, unregisters itself,
// and reloads the open tabs so they come back under no worker at all.
//
// WHAT IT DOES NOT TOUCH
//
// IndexedDB. The reader's saved stories are their content, not our cache, and killing the
// delivery mechanism is not a reason to burn the shelf. A reader whose worker is killed
// keeps their saved stories in the database; they simply cannot read them offline until a
// working worker ships again. If you genuinely need to clear shelf DATA — a schema
// disaster, not a caching one — that is a separate, louder decision: add
// `indexedDB.deleteDatabase('cs-shelf')` to the activate handler below and say so in the
// commit message.
//
// AFTER THE FIRE
//
// Restoring service means putting the real worker back at public/sw.js. Readers who
// already ran this one are unregistered, so they simply register the new one on their next
// visit to a page that calls registerShelfWorker() — no manual cleanup, no stuck state.
// ═══════════════════════════════════════════════════════════════════════════════════════

self.addEventListener('install', () => {
  // The one legitimate skipWaiting in the codebase. See above.
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    try {
      const keys = await caches.keys();
      await Promise.all(keys.map((k) => caches.delete(k)));
    } catch {}

    try {
      await self.registration.unregister();
    } catch {}

    // Reload every open tab so it re-fetches under no worker. Without this a reader sits
    // on a page still controlled by a worker that has just deleted its own caches.
    try {
      const clients = await self.clients.matchAll({ type: 'window' });
      for (const c of clients) {
        try { await c.navigate(c.url); } catch {}
      }
    } catch {}
  })());
});

// No fetch handler. An uncontrolled request is a request the browser handles itself, which
// is the state we are trying to return everyone to.
